### ISSUE TITLE
`Test_SAR.py` is giving wrong result and `Test_Synthetic.py` are not giving `valueError`

### ISSUE THREAD

**Issue by PalgunaGopireddy** [RTSIR/AGSDNet#1]
I have run `AGSDNet_SAR.py` and `AGSDNet_Synthetic.py`. They worked fine and stored `AGSDNet_SAR.h5` and `AGSDNet_Synthetic.h5` respectively in `./Pretrained_models/` folder.

Then I have run `Test_SAR.py` by replacing "7" with "0" in below lines (As I have only one GPU)
```
os.environ["CUDA_VISIBLE_DEVICES"]="0"
tf_device='/gpu:0'
```
also changed the weightsPath argument parser line to `./Pretrained_models/AGSDNet_SAR.h5` from `./Pretrained_models/AGSDNet.h5`

The output came as 
```
Trained Model is loaded
1/1 [==============================] - 2s 2s/step
ENL of image 1 is  nan
```
Then I went to `./Test_Results/SAR/` folder to check the output. The `1_Original` and `1_AGSDNet` images are given below respectively.
![1_Original](https://github.com/RTSIR/AGSDNet/assets/106730853/2c5668b4-8dd4-4248-aa6f-0c52e38e49f6)

![1_AGSDNet](https://github.com/RTSIR/AGSDNet/assets/106730853/2dc48cd3-2971-4e3c-9a41-9cada21ba7ed)

I do not know the why the output `1_AGSDNet` is coming full black.

The `Test_Synthetic.py` though giving the output, I do not see any difference in output and input.. Also it is showing the `userWarning`, `valueError` as shown below

```
Trained Model is loaded
1/1 [==============================] - 13s 13s/step
G:\Palguna\github\Denoising\AGSDNet-main\Test_Synthetic.py:87: UserWarning: Inputs have mismatched dtype.  Setting data_range based on image_true.
  psnr_val[i]=psnr(img1,z)
Traceback (most recent call last):
  File "G:\Palguna\github\Denoising\AGSDNet-main\Test_Synthetic.py", line 88, in <module>
    ssim_val[i]=ssim(img1,z)
  File "C:\Users\hp\AppData\Roaming\Python\Python39\site-packages\skimage\metrics\_structural_similarity.py", line 194, in structural_similarity
    raise ValueError(
ValueError: Since image dtype is floating point, you must specify the data_range parameter. Please read the documentation carefully (including the note). It is recommended that you always specify the data_range anyway.
```

How to resolve these?

**Comment by PalgunaGopireddy** [comment]
Resolved the Test_SAR.py is giving wrong result problem. These are the results after running `python Test_SAR.py`

> 2024-05-21 16:43:53.724310: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-21 16:43:54.236308: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 2774 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1
Trained Model is loaded
number of test image paths found: 3
number of test images found: 3
0
2024-05-21 16:43:56.024231: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8100
1/1 [==============================] - 2s 2s/step
[[0.21655515 0.17246416 0.12391371 ... 0.46519962 0.4904126  0.47073808]
 [0.21499228 0.17488503 0.11964407 ... 0.4490985  0.46325502 0.43469802]
 [0.26681364 0.24586172 0.22351988 ... 0.27374068 0.29103264 0.34468886]
 ...
 [0.8284523  0.8134507  0.68363345 ... 0.73216707 0.62773895 0.6300976 ]
 [0.77153057 0.6910215  0.43525994 ... 0.8017548  0.7069421  0.70512545]
 [0.74091685 0.5706268  0.2766504  ... 0.5416246  0.5313794  0.57280415]]
ENL of image 1 is  4.831081

The `1_Original` and `1_AGSDNet` images are given below respectively.
![1_Original](https://github.com/RTSIR/AGSDNet/assets/106730853/7f31cac6-ddf2-42c7-b29c-c45cc0d4a0d2)
![1_AGSDNet](https://github.com/RTSIR/AGSDNet/assets/106730853/7141c689-bdf1-4a52-9396-0e72136a5d01)

didn't try resolving `Test_Synthetic.py`. If you know how to resolve that `ValueError` occuring, post that solution.
